#+BIND: org-export-use-babel nil
#+TITLE: jeroen experiences during project
#+AUTHOR: jeroen jagt
#+EMAIL: <jpjagt@pm.me>
#+DATE: January 7, 2021
#+LATEX: \setlength\parindent{0pt}
#+LaTeX_HEADER: \usepackage{minted}
#+LATEX_HEADER: \usepackage[margin=0.8in]{geometry}
#+LATEX_HEADER_EXTRA:  \usepackage{mdframed}
#+LATEX_HEADER_EXTRA: \BeforeBeginEnvironment{minted}{\begin{mdframed}}
#+LATEX_HEADER_EXTRA: \AfterEndEnvironment{minted}{\end{mdframed}}
#+MACRO: NEWLINE @@latex:\\@@ @@html:<br>@@
#+PROPERTY: header-args :exports both :session jeroen :cache :results value
#+OPTIONS: ^:nil
#+LATEX_COMPILER: pdflatex

* data

** yaleb

two versions of the extended yaleb dataset exist; original and cropped. in the
cropped version, images are aligned and cropped. we use the cropped version, as
it is easier to work with.

** cifar100

the authors, following [20], repurpose the cifar100 dataset to become a
privacy-sensitive dataset. cifar100 has 100 fine classes, which are categorized
in 20 coarse super-classes. the fine classes are sensitive attribute, coarse
classes target attribute.

however, it is not said whether or not the fine classes are included as input
to the model. even though it would make sense because sensitive attributes are
also included in other datasets, it would be non-trivial to shape the input in
a 2d rectangle, and thus would not make a lot of sense when using a CNN.
